# -*- coding: utf-8 -*-"
#+STARTUP: overview indent

#+TITLE: StarVZ

#+OPTIONS: html-link-use-abs-url:nil html-postamble:auto
#+OPTIONS: html-preamble:t html-scripts:t html-style:t
#+OPTIONS: html5-fancy:nil tex:t
#+HTML_DOCTYPE: xhtml-strict
#+HTML_CONTAINER: div
#+DESCRIPTION:
#+KEYWORDS:
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+SUBTITLE:
#+INFOJS_OPT:
#+CREATOR: <a href="http://www.gnu.org/software/emacs/">Emacs</a> 25.2.2 (<a href="http://orgmode.org">Org</a> mode 9.0.1)
#+LATEX_HEADER:
#+EXPORT_EXCLUDE_TAGS: noexport
#+EXPORT_SELECT_TAGS: export
#+TAGS: noexport(n) deprecated(d)

StarVZ consists in a performance analysis workflow that combines the
power of the R language (and the =tidyverse= realm) and many auxiliary
tools to provide a consistent, flexible, extensible, fast, and
versatile framework for the performance analysis of task-based
applications that run on top of the [[http://starpu.gforge.inria.fr/][StarPU runtime]] (with its MPI layer
for multi-node support). Its goal is to provide a fruitful
prototypical environment to conduct hypothesis-checking for task-based
applications that run on heterogeneous (multi-GPU, multi-core)
multi-node experiments.

** Origin and Publications

A preliminary version of this framework has been released in the
companion website (check the reproducible paper link below) of this
workshop publication:

- Vinicius Garcia Pinto, Luka Stanisic, Arnaud Legrand, Lucas Mello
  Schnorr, Samuel Thibault, Vincent Danjean, "Analyzing Dynamic
  Task-Based Applications on Hybrid Platforms: An Agile Scripting
  Approach", In Third Workshop on Visual Performance Analysis, VPA@SC
  2016, Salt Lake, UT, USA, November 18, 2016,
  pp. 17-24, 2016.
  - [[http://perf-ev-runtime.gforge.inria.fr/vpa2016/][Reproducible Paper]]
  - [[https://doi.org/10.1109/VPA.2016.008][DOI]]

A second release of the framework is available in the companion
website of the following manuscript, which is currently under
evaluation in Wiley's Concurrent and Computation: Practice and
Experience:

- A Visual Performance Analysis Framework for Task-based Parallel
  Applications running on Hybrid Clusters. Vinicius Garcia Pinto,
  Lucas Mello Schnorr, Luka Stanisic, Arnaud Legrand, Samuel Thibault,
  Vincent Danjean. Submitted to Wiley's CCPE.
  - [[https://hal.inria.fr/hal-01616632/][Draft of this paper]]
  - [[https://gitlab.in2p3.fr/schnorr/ccpe2017][Companion website]]

** Content
- [[./INSTALL.org][Installation Instructions]]
