// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// integrateStepFunc
NumericVector integrateStepFunc(NumericVector x, NumericVector bounds, NumericVector values);
RcppExport SEXP _starvz_integrateStepFunc(SEXP xSEXP, SEXP boundsSEXP, SEXP valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bounds(boundsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(integrateStepFunc(x, bounds, values));
    return rcpp_result_gen;
END_RCPP
}
// lastest_task_c
DataFrame lastest_task_c(DataFrame df);
RcppExport SEXP _starvz_lastest_task_c(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(lastest_task_c(df));
    return rcpp_result_gen;
END_RCPP
}
// get_last_path
List get_last_path(DataFrame lasttask, CharacterVector selected_tasks);
RcppExport SEXP _starvz_get_last_path(SEXP lasttaskSEXP, SEXP selected_tasksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type lasttask(lasttaskSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type selected_tasks(selected_tasksSEXP);
    rcpp_result_gen = Rcpp::wrap(get_last_path(lasttask, selected_tasks));
    return rcpp_result_gen;
END_RCPP
}
// separate_res
DataFrame separate_res(DataFrame data);
RcppExport SEXP _starvz_separate_res(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type data(dataSEXP);
    rcpp_result_gen = Rcpp::wrap(separate_res(data));
    return rcpp_result_gen;
END_RCPP
}
// boost_shortest_path
NumericVector boost_shortest_path(int s, DataFrame df);
RcppExport SEXP _starvz_boost_shortest_path(SEXP sSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type s(sSEXP);
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(boost_shortest_path(s, df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_starvz_integrateStepFunc", (DL_FUNC) &_starvz_integrateStepFunc, 3},
    {"_starvz_lastest_task_c", (DL_FUNC) &_starvz_lastest_task_c, 1},
    {"_starvz_get_last_path", (DL_FUNC) &_starvz_get_last_path, 2},
    {"_starvz_separate_res", (DL_FUNC) &_starvz_separate_res, 1},
    {"_starvz_boost_shortest_path", (DL_FUNC) &_starvz_boost_shortest_path, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_starvz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
