# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrateStepFunc <- function(x, bounds, values) {
  .Call("_starvz_integrateStepFunc", PACKAGE = "starvz", x, bounds, values)
}

boost_shortest_path <- function(s, df) {
  .Call("_starvz_boost_shortest_path", PACKAGE = "starvz", s, df)
}
