suppressMessages(
    c(
        library(cowplot),
        library(data.tree),
        library(data.table),
        library(feather),
        library(gridExtra),
        library(logging),
        library(lpSolve),
        library(magrittr),
        library(pipeR),
        library(RColorBrewer),
        library(Rcpp),
        library(reshape2),
        library(tidyverse),
        library(zoo)));
